### ISSUE TITLE
Porting a Program to this UI

### ISSUE THREAD

**Issue by pngmafia** [juef17/LibreBridge#10]
I have a bridge program that can play as declarer. I'm trying to port it to this UI. Any suggestions on where to start? 
Thanks

**Comment by juef17** [comment]
Unfortunately, the UI is not nearly complete, and I haven't had the time or motivation to work on it for a while. Sorry!

**Comment by pngmafia** [comment]
Can you point me to any other open-source UI I can use to port my code?
Thanks

**Comment by juef17** [comment]
I know of no other, which is why I wanted to develop mine in the first place. Sorry! Your best bet is probably to create a new one, or complete mine...
