### ISSUE TITLE
README document

### ISSUE THREAD

**Issue by richardxing** [juef17/LibreBridge#9]
Hi, 

I am trying to run this program but don't know how to install it. Can you specify how to run qmake and make in README document? Thank you!

**Comment by juef17** [comment]
To be honest, I haven't had the chance to do anything with this project for two years, the AI is still non-existent, and build instructions are more complicated on Windows... so I can't really help right now. If you really want to run it, here's a [Windows binary](https://www.dropbox.com/s/ats2qahjqu3229l/Release.7z?dl=1).

That being said, I do plan to come back to it someday in the future, and pull requests are very welcome!

**Comment by richardxing** [comment]
> 
> 
> To be honest, I haven't had the chance to do anything with this project for two years, the AI is still non-existent, and build instructions are more complicated on Windows... so I can't really help right now. If you really want to run it, here's a [Windows binary](https://www.dropbox.com/s/ats2qahjqu3229l/Release.7z?dl=1).
> 
> That being said, I do plan to come back to it someday in the future, and pull requests are very welcome!

Thanks! How do you build it in Linux?

**Comment by juef17** [comment]
Honestly, all I remember is needed is to install qt, then in a terminal, head to the source directory and run qmake, then make. It really is all there was to it, as far as I can remember. You can then run the program by executing `./LibreBridge`
